# Generated by Django 6.0.1 on 2026-01-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_status', models.CharField(choices=[('OPEN', 'Open'), ('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='OPEN', help_text='Current status of this ticket.')),
                ('ticket_type', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INTRODUCTION', 'Introduction'), ('RECRUIT', 'Recruit for event'), ('CONFIRM', 'Confirm event participation')], default='UNKNOWN', help_text='Type for this ticket')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'P0 - Emergency (Do Now)'), (1, 'P1 - Very High'), (2, 'P2 - High'), (3, 'P3 - Normal'), (4, 'P4 - Low'), (5, 'P5 - Very Low')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User ticket is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, help_text='Contact this ticket relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='contacts.contact')),
                ('event', models.ForeignKey(blank=True, help_text='Event this ticket relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event')),
                ('reported_by', models.ForeignKey(blank=True, help_text='User that created this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketAuditlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('CREATED', 'Ticket created'), ('UPDATED', 'Ticket updated'), ('CLAIM', 'Ticket claimed'), ('UNCLAIMED', 'Ticket unclaimed'), ('STATUS', 'Ticket status changed'), ('CONTACT_RESPONSE', 'Contact responded'), ('COMMENT', 'New comment')], help_text='Type of event in ticket audit log')),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Optional structured context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User that created this entry (NULL means system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_logs_user', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
