# Generated by Django 6.0.1 on 2026-01-14 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tickets', '0002_ticketcomment_delete_ticketauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('INTRODUCTION', 'Introduction'), ('RECRUIT', 'Recruit for event'), ('CONFIRM', 'Confirm event participation')], default='UNKNOWN', max_length=50),
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_logs', to='contacts.contact')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
