# Generated by Django 6.0.1 on 2026-01-17 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tickets', '0003_ticketcomment_type_ticketauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAsks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('REJECTED', 'Rejected'), ('AGREED', 'Agreed'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('GHOSTED', 'Ghosted')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_logs', to='contacts.contact')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_asks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TicketAuditLog',
        ),
    ]
