# Generated by Django 6.0.1 on 2026-01-18 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tickets', '0004_ticketasks_delete_ticketauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketasks',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_asks', to='contacts.contact'),
        ),
    ]
