# Generated by Django 6.0.1 on 2026-01-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_address', models.CharField(blank=True, max_length=300, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('event_status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', help_text='Current status of this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('REJECTED', 'Rejected'), ('COMMITTED', 'Committed'), ('MAYBE', 'Maybe'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], default='UNKNOWN', help_text='Commitment level of the contact for this event', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='contacts.contact')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
            options={
                'db_table': 'event_participations',
                'indexes': [models.Index(fields=['event'], name='event_parti_event_i_10b565_idx'), models.Index(fields=['contact'], name='event_parti_contact_7a167a_idx'), models.Index(fields=['status'], name='event_parti_status_800e4a_idx')],
                'unique_together': {('event', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='UsersInEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_in_events',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user'], name='users_in_ev_user_id_da9cfd_idx'), models.Index(fields=['event'], name='users_in_ev_event_i_e29b4f_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
