#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Starting server..."

# Run migrations before starting server
python manage.py migrate

# Optionaly fill DB with fake data
if [ "${INSERT_FAKE_DATA}" = "1" ] || [ "${INSERT_FAKE_DATA}" = "true" ]; then
    python fake/main.py "${DATABASE_URL}"
fi
exec python manage.py runserver 0.0.0.0:8080
